### ISSUE TITLE
Email Signup Form

### ISSUE THREAD

**Issue by marckrejci** [Lumanary/lumanary.github.io#3]
Ryan, was wondering why our email signups are so low and it appears there is still an error with the email form on https://congo.io on the button reads “Let’s Go!”.

Users are STILL getting this error page: https://congo.us2.list-manage.com/subscribe/post?u=6451c2d7566ef74e80cf880ab&id=b3baad26d3

![Congo.png](http://content.cashewapp.io/api.github.com/marckrejci/20161220051843UTC/95636207-47f4-4683-8aee-4063826d1e3e.png)

**Comment by marckrejci** [comment]
FWIW, this does NOT happen when submitting via the footer form…

**Comment by ryandunnewold** [comment]
Fixed. Looks like the code from the footer didn't get copied over to the modal.

**Comment by ryandunnewold** [comment]
Not seeing this live yet, but when I open up an incognito tab it works.
